compile: p012_HighlyDivisibleTriangularNumber.c
	gcc -O3 p012_HighlyDivisibleTriangularNumber.c -o bin/p012_HighlyDivisibleTriangularNumber -lm

run: compile
	./bin/p012_HighlyDivisibleTriangularNumber

clean:
	rm bin/p012_HighlyDivisibleTriangularNumber



