compile: p002_EvenFibonacciNumbers.f90
	gfortran -O3 p002_EvenFibonacciNumbers.f90 -o bin/p002_EvenFibonacciNumbers

run: compile
	./bin/p002_EvenFibonacciNumbers

clean:
	rm bin/p002_EvenFibonacciNumbers


