! PROJECT EULER - PROBLEM 2
! EVEN FIBONACCI NUMBERS

! Each new term in the Fibonacci sequence is generated by adding the previous two terms.
! By starting with 1 and 2, the first 10 terms will be:

!       1,2,3,5,8,13,21,34,55,89, ...

! By considering the terms in the Fibonacci sequence whoose values do not exceed four million, 
! find the sum of the even-valued terms.

program main
    implicit none
    integer :: a=1, b=1, c=0, s=0

    do while (c<4000000)
        a = b + c
        b = a + c
        s = s + c
        c = a + b
    end do

    print *, s

end program main
