compile: p014_LongestCollatzSequence.c
	gcc -O3 p014_LongestCollatzSequence.c -o bin/p014_LongestCollatzSequence

run: compile
	./bin/p014_LongestCollatzSequence

clean:
	rm bin/p014_LongestCollatzSequence



