compile: p014_LongestCollatzSequence.f90
	gfortran -O3 p014_LongestCollatzSequence.f90 -o bin/p014_LongestCollatzSequence

run: compile
	./bin/p014_LongestCollatzSequence

clean:
	rm bin/p014_LongestCollatzSequence


