compile: p012_HighlyDivisibleTriangularNumber.f90
	gfortran -O3 p012_HighlyDivisibleTriangularNumber.f90 -o bin/p012_HighlyDivisibleTriangularNumber

run: compile
	./bin/p012_HighlyDivisibleTriangularNumber

clean:
	rm bin/p012_HighlyDivisibleTriangularNumber


