! PROJECT EULER - PROBLEM 12
! HIGHLY DIVISIBLE TRIANGULAR NUMBER

! The sequence of triangle numbers is generated by adding the natural numbers.
! So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
! The first ten terms would be:

!       1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

! Let us list the factors of the first seven triangle numbers:

!        1:1
!        3:1,3
!        6:1,2,3,6
!       10:1,2,5,10
!       15:1,3,5,15
!       21:1,2,7,21
!       28:1,2,4,7,14,28

! We can see that 28 is the first triangle number to have over five divisors.

! What is the value of the first triangle number to have over five hundred divisors?

function ndivs(k) result(n)
    integer, intent(in) :: k
    integer :: i, n
    
    n = 2
    do i = 2, floor(sqrt(real(k)))
        if ( mod(k,i) == 0 ) then
            n = n + 2
        end if
    end do

end function ndivs

program main
    implicit none
    integer :: i=1, n=1, tri=1
    integer :: ndivs
    
    do while ( n < 500 )
        i = i + 1
        tri = tri + i
        n = ndivs(tri)
        ! print *, tri, n
    end do
    
    print *, tri, n

end program main