// PROJECT EULER - PROBLEM 2
// EVEN FIBONACCI NUMBERS

// https://projecteuler.net/problem=2


// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:

//     1,2,3,5,8,13,21,34,55,89, ...

// By considering the terms in the Fibonacci sequence whoose values do not exceed four million, 
// find the sum of the even-valued terms.


#include <stdio.h>

int evenFibSum(int lim);


int main(void) {
    printf("%i\n", evenFibSum(4000000));
}


// Returns the sum of all even-valued Fibonacci numbers below lim
int evenFibSum(int lim) {
    // Starting with a=1 and b=1, every third term c is even:
    //      1,1,  2,  3,5,  8,  13,21,  34,  55,89, ...

    int a=1, b=1, c=0, sum=0;

    while (c < lim) {
        // Add even term
        sum += c;

        // Get next 3 terms
        c = a + b;
        a = b + c;
        b = c + a;
    }

    return sum;
}
